# Generated by Django 5.0 on 2023-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_address', models.TextField()),
                ('employee_phone_number', models.CharField(max_length=15)),
                ('employee_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
